title: Home [ðŸ©] Team
author: jbarrettsteiner
email: donut-tees@domomi.com
description: > # this means to ignore newlines until "baseurl:"
  Wear a holy donut for your home team. You can wear holy donuts with your friends and family. 
  We created the Donut Holy Tee for people to spark conversations, create memories and join our growing Home [ ] Team.
# social links
twitter_username: jbarrettsteiner # DO NOT include the @ character, or else the build will fail!
github_username:  jbarrettsteiner # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepag
